### ISSUE TITLE
后端接口跨域

### ISSUE THREAD

**Issue by Erik5169** [lerry903/RuoYi#1]
博主的后端服务是否支持跨域访问呢？

**Comment by lerry903** [comment]
目前不支持，不过spring boot对跨域设置比较简单。可自行配置

**Comment by Erik5169** [comment]
系统登录后， 所有的接口请求都必须传递哪些字段呢？ 系统接口的swg页面中没有对必填非必填参数做说明， 在浏览器调试中，发现Cookie中带了一些值，Cookie: pgv_pvi=1136267264; pgv_si=s9633105920; JSESSIONID=0741d5b0-bcd1-41d4-8cf5-b2ef0a85a07e ，这些值哪些是必须的呢？

**Comment by lerry903** [comment]
JSESSIONID是必须的参数

**Comment by Erik5169** [comment]
JSESSIONID ,是后端登录的时候传给前端的吗， 前端想跨域访问后端的接口的话， 需要后端服务设置跨域， 前端拿到JSESSIONID，放到Cookie中，以后每次请求都带上， 就能拿到接口数据了吧

**Comment by lerry903** [comment]
老哥。你是没基础么？

**Comment by Erik5169** [comment]
我不懂后端， 我写前端的哈

**Comment by lerry903** [comment]
OK，这个JSESSIONID是后端给前端的，前端每次请求的时候不需要做特殊处理，调用后端的时候会自动带上这个ID。另外，跨域的设置可以在后端设置也可以在前端通过jsonp的形式访问，不过这有限制。当然也可用反向代理的方式来解决跨域。方法有多种，看自己的方便

**Comment by Erik5169** [comment]
现在写了一套系统管理的前端单页应用，参考博主的， 想用博主的后端接口

**Comment by lerry903** [comment]
那还有一种方式，将自己的前端页面替换现在系统里面的前端页面。这样前端和后端都部署在一起，所以自然也不会有跨域的问题了

**Comment by Erik5169** [comment]
好的， 谢谢博主

**Comment by lerry903** [comment]
没啥事

**Comment by Erik5169** [comment]
hello , 博主， 我前端通过反向代理， 访问您这个项目的接口， 访问登陆接口的时候， 总是报500 的错误，能帮忙看一下吗？
<img width="457" alt="屏幕快照 2019-03-19 上午11 32 12" src="https://user-images.githubusercontent.com/25293699/54578444-caa6d300-4a3a-11e9-9c8f-6ae26d098ae4.png">
<img width="274" alt="屏幕快照 2019-03-19 上午11 32 29" src="https://user-images.githubusercontent.com/25293699/54578462-d7c3c200-4a3a-11e9-8bdf-d7a21cb2662e.png">
<img width="499" alt="屏幕快照 2019-03-19 上午11 32 23" src="https://user-images.githubusercontent.com/25293699/54578473-df836680-4a3a-11e9-9d5a-2050b8cf6a50.png">
<img width="290" alt="屏幕快照 2019-03-19 上午11 32 35" src="https://user-images.githubusercontent.com/25293699/54578486-e7430b00-4a3a-11e9-9e84-766cf6e1cee5.png">
